services:
  - type: web
    name: cropvision-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements-production.txt && curl -fL --retry 3 -o models/model.keras https://huggingface.co/rarfileexe/Plant-Disease-Detector/resolve/main/model_4_mobilenet_finetuned.keras
    startCommand: gunicorn --workers 1 --timeout 120 'run:app'
    envVars:
      - key: CORS_ORIGINS
        sync: false
